CREATE DATABASE IF NOT EXISTS EVCHARGING;

CREATE USER IF NOT EXISTS 'central'@'%' IDENTIFIED BY 'central-passwd';
CREATE USER IF NOT EXISTS 'registry'@'%' IDENTIFIED BY 'registry-passwd';

GRANT ALL PRIVILEGES ON EVCHARGING.* TO 'central'@'%';
GRANT ALL PRIVILEGES ON EVCHARGING.* TO 'registry'@'%';
FLUSH PRIVILEGES;

USE EVCHARGING;
