FROM python:3.12-alpine

# Install kafka dependency
RUN pip install confluent-kafka

# set directory where src is stored
WORKDIR /usr/src/EV_Driver

# copy files into image
COPY . .

# Do not forget the comma
ENTRYPOINT [ "python", "main.py" ]